module TiposProcesosDeSistemas
    
  PROCESAR_LIQUIDACION_SUMAR = 1

  GENERAR_CUASIFACTURAS_LIQUIDACION_SUMAR = 2

  REGISTO_MASIVO_DE_PRESTACIONES = 3 

  REGISTO_MASIVO_DE_BENEFICIARIOS = 4
  
end
