module TiposProcesosDeSistemas
    
  PROCESAR_LIQUIDACION_SUMAR = 1

  GENERAR_CUASIFACTURAS_LIQUIDACION_SUMAR = 2

  REGISTO_MASIVO_DE_PRESTACIONES = 3 

  REGISTO_MASIVO_DE_BENEFICIARIOS = 4
  
  CIERRE_DE_PADRON = 5
  
  ACTUALIZACION_DE_LAS_NOVEDADES = 6

  ACTUALIZACION_DEL_PADRON = 7
end
