# Utilizamos el motor PostgreSQL
production:
  adapter: postgresql
  encoding: unicode
  database: nacer
  username: nacer_adm

development:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: nacer
  username: nacer_adm
  password: 
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  encoding: unicode
  database: nacer_test
  username: nacer_adm
