# MySQL.  Versions 4.1 and 5.0 are recommended.
#
#
# Be sure to use new-style password hashing:
#   http://dev.mysql.com/doc/refman/5.0/en/old-client.html
development:
  adapter: postgresql
  encoding: unicode
  database: nacer_dev
  username: nacer_adm

test:
  adapter: postgresql
  encoding: unicode
  database: nacer_dev_test
  username: nacer_adm

production:
  adapter: postgresql
  encoding: unicode
  database: nacer_dev_production
  username: nacer_adm

