# Utilizamos el motor PostgreSQL
production:
  adapter: postgresql
  encoding: unicode
  database: nacer
  username: nacer_adm
  password: sgsp_350-Mendoza

development:
  adapter: postgresql
  encoding: unicode
  database: nacer
  host: localhost
  pool: 5
  username: nacer_adm
  password: sgsp_350-Mendoza
  port: 5433

test:
  adapter: postgresql
  encoding: unicode
  database: nacer_test
  username: nacer_adm