# -*- encoding : utf-8 -*-
# Datos precargados al inicializar el sistema
DatoReportable.create([
        { #:id => 1,
          :nombre => "Peso (en kilogramos)",
          :codigo => "PKG",
          :tipo_postgres => "numeric(5,2)",
          :tipo_ruby => "Float",
          :enumerable => false,
          :integra_grupo => false,
          :opciones_de_formateo => "{:size => 6}" },
        { #:id => 2,
          :nombre => "Talla (en metros)",
          :codigo => "TM",
          :tipo_postgres => "numeric(3,2)",
          :tipo_ruby => "Float",
          :enumerable => false,
          :integra_grupo => false,
          :opciones_de_formateo => "{:size => 6}" },
        { #:id => 3,
          :nombre => "Edad gestacional (en semanas)",
          :codigo => "EG",
          :tipo_postgres => "numeric(3,1)",
          :tipo_ruby => "Float",
          :enumerable => false,
          :integra_grupo => false },
        { #:id => 4,
          :nombre_de_grupo => "Tensión arterial",
          :nombre => "Sistólica",
          :codigo => "TAS",
          :tipo_postgres => "int4",
          :tipo_ruby => "Integer",
          :enumerable => false,
          :integra_grupo => true,
          :orden_de_grupo => 1,
          :opciones_de_formateo => "{:size => 6}" },
        { #:id => 5,
          :nombre_de_grupo => "Tensión arterial",
          :nombre => "Diastólica",
          :codigo => "TAD",
          :tipo_postgres => "int4",
          :tipo_ruby => "Integer",
          :enumerable => false,
          :integra_grupo => true,
          :orden_de_grupo => 2,
          :opciones_de_formateo => "{:size => 6}" },
        { #:id => 6,
          :nombre_de_grupo => "Índice CPOD",
          :nombre => "Caries",
          :codigo => "CPOD_C",
          :tipo_postgres => "int4",
          :tipo_ruby => "Integer",
          :enumerable => false,
          :integra_grupo => true,
          :orden_de_grupo => 1,
          :opciones_de_formateo => "{:size => 3}" },
        { #:id => 7,
          :nombre_de_grupo => "Índice CPOD",
          :nombre => "Perdidos",
          :codigo => "CPOD_P",
          :tipo_postgres => "int4",
          :tipo_ruby => "Integer",
          :enumerable => false,
          :integra_grupo => true,
          :orden_de_grupo => 2,
          :opciones_de_formateo => "{:size => 3}" },
        { #:id => 8,
          :nombre_de_grupo => "Índice CPOD",
          :nombre => "Obturados",
          :codigo => "CPOD_O",
          :tipo_postgres => "int4",
          :tipo_ruby => "Integer",
          :enumerable => false,
          :integra_grupo => true,
          :orden_de_grupo => 3,
          :opciones_de_formateo => "{:size => 3}" },
        { #:id => 9,
          :nombre => "Hemoglobina",
          :codigo => "HB",
          :tipo_postgres => "numeric(3,1)",
          :tipo_ruby => "Float",
          :enumerable => false,
          :integra_grupo => false,
          :opciones_de_formateo => "{:size => 6}" },
        { #:id => 10,
          :nombre => "Diagnóstico",
          :codigo => "DIAG",
          :tipo_postgres => "varchar(255)",
          :tipo_ruby => "String",
          :enumerable => false,
          :integra_grupo => false,
          :opciones_de_formateo => "{:size => 60}" },
        { #:id => 11,
          :nombre => "Aspiración manual endouterina (AMEU)",
          :codigo => "AMEU",
          :tipo_postgres => "int4",
          :tipo_ruby => "Integer",
          :enumerable => true,
          :clase_para_enumeracion => "SiNo",
          :integra_grupo => false },
        { #:id => 12,
          :nombre => "Peso del recién nacido",
          :codigo => "PG",
          :tipo_postgres => "int4",
          :tipo_ruby => "Integer",
          :enumerable => false,
          :integra_grupo => false,
          :opciones_de_formateo => "{:size => 6}" },
        { #:id => 13,
          :nombre => "Fecha de parto",
          :codigo => "FP",
          :tipo_postgres => "date",
          :tipo_ruby => "Date",
          :enumerable => false,
          :integra_grupo => false },
        { #:id => 14,
          :nombre_de_grupo => "Días de internación",
          :nombre => "En UTI",
          :codigo => "UTI",
          :tipo_postgres => "int4",
          :tipo_ruby => "Integer",
          :enumerable => false,
          :integra_grupo => true,
          :orden_de_grupo => 1,
          :opciones_de_formateo => "{:size => 3}" },
        { #:id => 15,
          :nombre_de_grupo => "Días de internación",
          :nombre => "En sala común",
          :codigo => "SC",
          :tipo_postgres => "int4",
          :tipo_ruby => "Integer",
          :enumerable => false,
          :integra_grupo => true,
          :orden_de_grupo => 2,
          :opciones_de_formateo => "{:size => 3}" },
        { #:id => 16,
          :nombre_de_grupo => "Resultados del estudio",
          :nombre => "Oído derecho",
          :codigo => "ROD",
          :tipo_postgres => "varchar(255)",
          :tipo_ruby => "String",
          :enumerable => false,
          :integra_grupo => true,
          :orden_de_grupo => 1,
          :opciones_de_formateo => "{:size => 3}" },
        { #:id => 17,
          :nombre_de_grupo => "Resultados del estudio",
          :nombre => "Oído izquierdo",
          :codigo => "ROI",
          :tipo_postgres => "varchar(255)",
          :tipo_ruby => "String",
          :enumerable => false,
          :integra_grupo => true,
          :orden_de_grupo => 2,
          :opciones_de_formateo => "{:size => 3}" },
        { #:id => 18,
          :nombre => "Grado de retinopatía",
          :codigo => "ROP",
          :tipo_postgres => "int4",
          :tipo_ruby => "Integer",
          :enumerable => false,
          :integra_grupo => false,
          :opciones_de_formateo => "{:size => 6}" },
        { #:id => 19,
          :nombre_de_grupo => "Detalle de la internación",
          :nombre => "Días de estada pre-quirúrgicos",
          :codigo => "CCPQ",
          :tipo_postgres => "int4",
          :tipo_ruby => "Integer",
          :enumerable => false,
          :integra_grupo => true,
          :orden_de_grupo => 1,
          :opciones_de_formateo => "{:size => 3}" },
        { #:id => 20,
          :nombre_de_grupo => "Detalle de la internación",
          :nombre => "Días de estada post-quirúrgica en UTI",
          :codigo => "CCTQU",
          :tipo_postgres => "int4",
          :tipo_ruby => "Integer",
          :enumerable => false,
          :integra_grupo => true,
          :orden_de_grupo => 2,
          :opciones_de_formateo => "{:size => 3}" },
        { #:id => 21,
          :nombre_de_grupo => "Detalle de la internación",
          :nombre => "Días de medicación post-quirúrgica",
          :codigo => "CCTQM",
          :tipo_postgres => "int4",
          :tipo_ruby => "Integer",
          :enumerable => false,
          :integra_grupo => true,
          :orden_de_grupo => 3,
          :opciones_de_formateo => "{:size => 3}" },
        { #:id => 22,
          :nombre_de_grupo => "Detalle de la internación",
          :nombre => "Días de estada post-quirúrgica en UTI con medicación",
          :codigo => "CCTQUM",
          :tipo_postgres => "int4",
          :tipo_ruby => "Integer",
          :enumerable => false,
          :integra_grupo => true,
          :orden_de_grupo => 4,
          :opciones_de_formateo => "{:size => 3}" },
        { #:id => 23,
          :nombre_de_grupo => "Detalle de la internación",
          :nombre => "Días de estada post-quirúrgica en sala común",
          :codigo => "CCTQS",
          :tipo_postgres => "int4",
          :tipo_ruby => "Integer",
          :enumerable => false,
          :integra_grupo => true,
          :orden_de_grupo => 5,
          :opciones_de_formateo => "{:size => 3}" }
])
