# -*- encoding : utf-8 -*-
# Datos precargados al inicializar el sistema
DatoReportable.create([
        { #:id => 1,
          :nombre => "Peso (en kilogramos)",
          :codigo => "PKG",
          :tipo_postgres => "numeric(5,2)",
          :tipo_ruby => "big_decimal",
          :enumerable => false,
          :integra_grupo => false,
          :opciones_de_formateo => "{:size => 6}" },
        { #:id => 2,
          :nombre => "Talla (en metros)",
          :codigo => "TM",
          :tipo_postgres => "numeric(3,2)",
          :tipo_ruby => "big_decimal",
          :enumerable => false,
          :integra_grupo => false,
          :opciones_de_formateo => "{:size => 6}" },
        { #:id => 3,
          :nombre => "Edad gestacional (en semanas)",
          :codigo => "EG",
          :tipo_postgres => "numeric(3,1)",
          :tipo_ruby => "big_decimal",
          :enumerable => false,
          :integra_grupo => false,
          :opciones_de_formateo => "{:size => 6}" },
        { #:id => 4,
          :nombre_de_grupo => "Tensión arterial",
          :codigo_de_grupo => "ta",
          :nombre => "Sistólica",
          :codigo => "TAS",
          :tipo_postgres => "integer",
          :tipo_ruby => "integer",
          :enumerable => false,
          :integra_grupo => true,
          :orden_de_grupo => 1,
          :opciones_de_formateo => "{:size => 6}" },
        { #:id => 5,
          :nombre_de_grupo => "Tensión arterial",
          :codigo_de_grupo => "ta",
          :nombre => "Diastólica",
          :codigo => "TAD",
          :tipo_postgres => "integer",
          :tipo_ruby => "integer",
          :enumerable => false,
          :integra_grupo => true,
          :orden_de_grupo => 2,
          :opciones_de_formateo => "{:size => 6}" },
        { #:id => 6,
          :nombre_de_grupo => "Índice CPOD",
          :codigo_de_grupo => "cpod",
          :nombre => "Caries",
          :codigo => "CPOD_C",
          :tipo_postgres => "integer",
          :tipo_ruby => "integer",
          :enumerable => false,
          :integra_grupo => true,
          :orden_de_grupo => 1,
          :opciones_de_formateo => "{:size => 3}" },
        { #:id => 7,
          :nombre_de_grupo => "Índice CPOD",
          :codigo_de_grupo => "cpod",
          :nombre => "Perdidos",
          :codigo => "CPOD_P",
          :tipo_postgres => "integer",
          :tipo_ruby => "integer",
          :enumerable => false,
          :integra_grupo => true,
          :orden_de_grupo => 2,
          :opciones_de_formateo => "{:size => 3}" },
        { #:id => 8,
          :nombre_de_grupo => "Índice CPOD",
          :codigo_de_grupo => "cpod",
          :nombre => "Obturados",
          :codigo => "CPOD_O",
          :tipo_postgres => "integer",
          :tipo_ruby => "integer",
          :enumerable => false,
          :integra_grupo => true,
          :orden_de_grupo => 3,
          :opciones_de_formateo => "{:size => 3}" },
        { #:id => 9,
          :nombre => "Hemoglobina",
          :codigo => "HB",
          :tipo_postgres => "numeric(3,1)",
          :tipo_ruby => "big_decimal",
          :enumerable => false,
          :integra_grupo => false,
          :opciones_de_formateo => "{:size => 6}" },
        { #:id => 10,
          :nombre => "Diagnóstico",
          :codigo => "DIAG",
          :tipo_postgres => "text",
          :tipo_ruby => "text",
          :enumerable => false,
          :integra_grupo => false,
          :opciones_de_formateo => "{:size => 60}" },
        { #:id => 11,
          :nombre => "Aspiración manual endouterina (AMEU)",
          :codigo => "AMEU",
          :tipo_postgres => "integer",
          :tipo_ruby => "integer",
          :enumerable => true,
          :clase_para_enumeracion => "SiNo",
          :integra_grupo => false },
        { #:id => 12,
          :nombre => "Peso del recién nacido",
          :codigo => "PG",
          :tipo_postgres => "integer",
          :tipo_ruby => "integer",
          :enumerable => false,
          :integra_grupo => false,
          :opciones_de_formateo => "{:size => 6}" },
        { #:id => 13,
          :nombre => "Fecha de parto",
          :codigo => "FP",
          :tipo_postgres => "date",
          :tipo_ruby => "date",
          :enumerable => false,
          :integra_grupo => false },
        { #:id => 14,
          :nombre_de_grupo => "Días de internación",
          :codigo_de_grupo => "di",
          :nombre => "En UTI",
          :codigo => "UTI",
          :tipo_postgres => "integer",
          :tipo_ruby => "integer",
          :enumerable => false,
          :integra_grupo => true,
          :orden_de_grupo => 1,
          :opciones_de_formateo => "{:size => 3}" },
        { #:id => 15,
          :nombre_de_grupo => "Días de internación",
          :codigo_de_grupo => "di",
          :nombre => "En sala común",
          :codigo => "SC",
          :tipo_postgres => "integer",
          :tipo_ruby => "integer",
          :enumerable => false,
          :integra_grupo => true,
          :orden_de_grupo => 2,
          :opciones_de_formateo => "{:size => 3}" },
        { #:id => 16,
          :nombre_de_grupo => "Resultados del estudio",
          :codigo_de_grupo => "re",
          :nombre => "Oído derecho",
          :codigo => "ROD",
          :tipo_postgres => "text",
          :tipo_ruby => "text",
          :enumerable => false,
          :integra_grupo => true,
          :orden_de_grupo => 1,
          :opciones_de_formateo => "{:size => 3}" },
        { #:id => 17,
          :nombre_de_grupo => "Resultados del estudio",
          :codigo_de_grupo => "re",
          :nombre => "Oído izquierdo",
          :codigo => "ROI",
          :tipo_postgres => "text",
          :tipo_ruby => "text",
          :enumerable => false,
          :integra_grupo => true,
          :orden_de_grupo => 2,
          :opciones_de_formateo => "{:size => 3}" },
        { #:id => 18,
          :nombre => "Grado de retinopatía",
          :codigo => "ROP",
          :tipo_postgres => "integer",
          :tipo_ruby => "integer",
          :enumerable => false,
          :integra_grupo => false,
          :opciones_de_formateo => "{:size => 6}" },
        { #:id => 19,
          :nombre_de_grupo => "Detalle de la internación",
          :codigo_de_grupo => "di",
          :nombre => "Días de estada pre-quirúrgicos",
          :codigo => "DEPREQ",
          :tipo_postgres => "integer",
          :tipo_ruby => "integer",
          :enumerable => false,
          :integra_grupo => true,
          :orden_de_grupo => 1,
          :opciones_de_formateo => "{:size => 3}" },
        { #:id => 20,
          :nombre_de_grupo => "Detalle de la internación",
          :codigo_de_grupo => "di",
          :nombre => "Días de estada post-quirúrgica en UTI",
          :codigo => "DEPOSTQU",
          :tipo_postgres => "integer",
          :tipo_ruby => "integer",
          :enumerable => false,
          :integra_grupo => true,
          :orden_de_grupo => 2,
          :opciones_de_formateo => "{:size => 3}" },
        { #:id => 21,
          :nombre_de_grupo => "Detalle de la internación",
          :codigo_de_grupo => "di",
          :nombre => "Días de estada post-quirúrgica en cuidados intermedios",
          :codigo => "DEPOSTQCI",
          :tipo_postgres => "integer",
          :tipo_ruby => "integer",
          :enumerable => false,
          :integra_grupo => true,
          :orden_de_grupo => 3,
          :opciones_de_formateo => "{:size => 3}" },
        { #:id => 22,
          :nombre_de_grupo => "Detalle de la internación",
          :codigo_de_grupo => "di",
          :nombre => "Días de medicación post-quirúrgica",
          :codigo => "DMPOSTQ",
          :tipo_postgres => "integer",
          :tipo_ruby => "integer",
          :enumerable => false,
          :integra_grupo => true,
          :orden_de_grupo => 4,
          :opciones_de_formateo => "{:size => 3}" },
        { #:id => 23,
          :nombre_de_grupo => "Detalle de la internación",
          :codigo_de_grupo => "di",
          :nombre => "Días de estada post-quirúrgica en UTI con medicación",
          :codigo => "DEPOSTQUM",
          :tipo_postgres => "integer",
          :tipo_ruby => "integer",
          :enumerable => false,
          :integra_grupo => true,
          :orden_de_grupo => 5,
          :opciones_de_formateo => "{:size => 3}" },
        { #:id => 24,
          :nombre_de_grupo => "Detalle de la internación",
          :codigo_de_grupo => "di",
          :nombre => "Días de estada post-quirúrgica en sala común",
          :codigo => "DEPOSTQSC",
          :tipo_postgres => "integer",
          :tipo_ruby => "integer",
          :enumerable => false,
          :integra_grupo => true,
          :orden_de_grupo => 6,
          :opciones_de_formateo => "{:size => 3}" },
        { #:id => 25,
          :nombre => "Valor cubierto (costo de la última compra en pesos)",
          :codigo => "VC",
          :tipo_postgres => "numeric(15,4)",
          :tipo_ruby => "big_decimal",
          :enumerable => false,
          :integra_grupo => false,
          :opciones_de_formateo => "{:size => 10}" },
        { #:id => 26,
          :nombre => "Talla (en centímetros)",
          :codigo => "TCM",
          :tipo_postgres => "integer",
          :tipo_ruby => "integer",
          :enumerable => false,
          :integra_grupo => false,
          :opciones_de_formateo => "{:size => 6}" },
        { #:id => 27,
          :nombre => "Perímetro cefálico (en centímetros)",
          :codigo => "PC",
          :tipo_postgres => "integer",
          :tipo_ruby => "integer",
          :enumerable => false,
          :integra_grupo => false,
          :opciones_de_formateo => "{:size => 6}" },
        { #:id => 28,
          :nombre => "Grado de hipoacusia",
          :codigo => "GH",
          :tipo_postgres => "text",
          :tipo_ruby => "text",
          :enumerable => false,
          :integra_grupo => false,
          :opciones_de_formateo => "{:size => 30}" },
        { #:id => 29,
          :nombre_de_grupo => "Índice CeO",
          :codigo_de_grupo => "ceo",
          :nombre => "Caries",
          :codigo => "CEO_C",
          :tipo_postgres => "integer",
          :tipo_ruby => "integer",
          :enumerable => false,
          :integra_grupo => true,
          :orden_de_grupo => 1,
          :opciones_de_formateo => "{:size => 3}" },
        { #:id => 30,
          :nombre_de_grupo => "Índice CeO",
          :codigo_de_grupo => "ceo",
          :nombre => "Extracción indicada",
          :codigo => "CEO_E",
          :tipo_postgres => "integer",
          :tipo_ruby => "integer",
          :enumerable => false,
          :integra_grupo => true,
          :orden_de_grupo => 2,
          :opciones_de_formateo => "{:size => 3}" },
        { #:id => 31,
          :nombre_de_grupo => "Índice CeO",
          :codigo_de_grupo => "ceo",
          :nombre => "Obturados",
          :codigo => "CEO_O",
          :tipo_postgres => "integer",
          :tipo_ruby => "integer",
          :enumerable => false,
          :integra_grupo => true,
          :orden_de_grupo => 3,
          :opciones_de_formateo => "{:size => 3}" },
        { #:id => 32,
          :nombre => "Clasificación (severidad)",
          :codigo => "ASM",
          :tipo_postgres => "text",
          :tipo_ruby => "text",
          :enumerable => false,
          :integra_grupo => false,
          :opciones_de_formateo => "{:size => 30}" }
])
