# Datos precargados al inicializar el sistema
DependenciaAdministrativa.create([
        { #:id => 1,
          :nombre => "Ministerio de salud provincial",
          :tipo_de_dependencia => "P" },
        { #:id => 2,
          :nombre => "Municipalidad",
          :tipo_de_dependencia => "M" },
        { #:id => 3,
          :nombre => "Otras instituciones públicas provinciales",
          :tipo_de_dependencia => "P" },
        { #:id => 4,
          :nombre => "Ministerio de salud nacional",
          :tipo_de_dependencia => "N" },
        { #:id => 5,
          :nombre => "Otras instituciones públicas nacionales",
          :tipo_de_dependencia => "N" },
        { #:id => 6,
          :nombre => "Obras sociales",
          :tipo_de_dependencia => "O" },
        { #:id => 7,
          :nombre => "Organizaciones no gubernamentales",
          :tipo_de_dependencia => "G" },
        { #:id => 8,
          :nombre => "Instituciones privadas",
          :tipo_de_dependencia => "R" },
        { #:id => 9,
          :nombre => "Profesionales independientes",
          :tipo_de_dependencia => "I" },
        { #:id => 10,
          :nombre => "Nacional, provincial, municipal",
          :tipo_de_dependencia => "T" },
])
