# -*- encoding : utf-8 -*-
# Datos precargados al inicializar el sistema
MotivoDeRechazo.create([
        { #:id => 6,
          nombre: "La prestación no se acompañó por la documentación respaldatoria requerida",
          categoria: "Administrativa" },
        { #:id => 7,
          :nombre => "La documentación respaldatoria se encuentra incompleta",
          categoria: "Administrativa"  },
        { #:id => 8,
          :nombre => "La documentación respaldatoria no se encuentra autorizada por el responsable",
          categoria: "Administrativa"  },
        { #:id => 9,
          :nombre => "Los datos de la documentación respaldatoria no condicen con los registrados",
          categoria: "Administrativa"  },
        { #:id => 10,
          :nombre => "La prestación no es elegible para su pago",
          categoria: "Administrativa"  },
        { #:id => 11,
          nombre: "Rechazada por improcedente",
          categoria: "Administrativa"  },
        {# :id => 12, 
          nombre: "La prestación no corresponde para el afiliado", 
          categoria: "Medica"},
        {# :id => 13, 
          nombre: "La prestación se presto fuera del periodo permitido", 
          categoria: "Medica"},
        {# :id => 14, 
          nombre: "Los datos reportados no condicen con el diagnostico", 
          categoria: "Medica"},
        {# :id => 15, 
          nombre: "Rechazada por improcedente", 
          categoria: "Medica"},
])
